language: haskell

ghc:
  - '7.8'

before_install:
  - cabal update
  - travis/cabal-apt-install --only-dependencies --force-reinstall $mode

install:
  - cabal configure $mode
  - cabal build

script:
  - $script

env:
  - mode="--enable-tests" script="cabal test --show-details=always"

