language: haskell
sudo: false

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - happy-1.19.4
      - alex-3.1.3
      - ghc-7.10.2
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --version

script:
  - stack setup
  - stack build --no-terminal
  - stack test  --test-arguments --plain

cache:
  directories:
  - $HOME/.stack


### OLD new stuff

#language: haskell
#ghc:
#  - '7.8'
##  - '7.10'
#sudo: false
#
#addons:
#  apt:
#    sources:
#      - hvr-ghc
#    packages:
#      - happy-1.19.4
#      - alex-3.1.3
#      - cabal-install-1.22
#
#before_install:
#  - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:/opt/cabal/1.22/bin:$PATH
#  - cabal update
#
#install:
#  - cabal install --only-dependencies --enable-tests --reorder-goals
#
#script:
#  - cabal configure --enable-tests && cabal build && cabal test

